sudo: false
language: java
jdk:
  - oraclejdk8
env:
  global:
    secure: "KncKGamS99AWFQNs2L4a3s65BdNvP07yD/fulNZA+tsBNVLgxsieXkRdzrA5Efxbd5PvnBJuLkYgjPFSFh4uPNwijH5PnZMsSYlnSFIbLyGAIkWx2cJeUoDXOOrbHIeRmCDS6gZjs9sUZHrVlhF9B/19txf4XUjpd/6slqdsEng="  # BINTRAY_API_KEY
  matrix:
    - HV_GROUP_ID=org.hibernate HV_VERSION=4.3.2.Final
    - HV_GROUP_ID=org.hibernate HV_VERSION=5.0.3.Final DEPLOY=yes
    - HV_GROUP_ID=org.hibernate HV_VERSION=5.1.3.Final
    - HV_GROUP_ID=org.hibernate HV_VERSION=5.2.5.Final
    - HV_GROUP_ID=org.hibernate HV_VERSION=5.3.5.Final
    - HV_GROUP_ID=org.hibernate HV_VERSION=5.4.1.Final
    - HV_GROUP_ID=org.hibernate.validator HV_VERSION=6.0.0.Final
    - HV_GROUP_ID=org.hibernate.validator HV_VERSION=6.0.3.Final
    - HV_GROUP_ID=org.hibernate.validator HV_VERSION=6.0.4.Final

# Cache local Maven repository
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -Rf ~/.m2/repository/cz/jirutka/validator/validator-collection

install:
  - mvn install -Ptest-different-hv-version -Dhv.groupId.test=${HV_GROUP_ID} -Dhv.version.test=${HV_VERSION} -DskipTests=true --batch-mode
script:
  - mvn verify -Ptest-different-hv-version -Dhv.groupId.test=${HV_GROUP_ID} -Dhv.version.test=${HV_VERSION} --batch-mode
after_success:
  - mvn jacoco:report coveralls:report

deploy:
  provider: script
  script: script/travis-deploy
  skip_cleanup: true
  on:
    branch: master
    jdk: oraclejdk8
    condition: "$DEPLOY = yes"
